model_name_or_path: Qwen/Qwen2-VL-7B-Instruct
template: qwen2_vl
trust_remote_code: true
stage: sft
do_train: true
finetuning_type: lora
freeze_vision_tower: true
dataset: webvid_formatted
dataset_dir: /home/mukul.ranjan/projects/video-vlm/qwen-vl-video/data
cutoff_len: 2048
preprocessing_num_workers: 1
lora_rank: 64
lora_alpha: 128
lora_dropout: 0.05
lora_target: q_proj,v_proj
output_dir: /l/users/mukul.ranjan/video_data/model
logging_steps: 10
save_steps: 100
save_total_limit: 3
per_device_train_batch_size: 4
gradient_accumulation_steps: 4
learning_rate: 0.0002
num_train_epochs: 3
warmup_ratio: 0.1
bf16: true
seed: 42
gradient_checkpointing: true
